# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
# after-startup-command = ['exec-and-forget sketchybar']
after-startup-command = ['exec-and-forget borders']

# Notify Sketchybar about workspace change
# exec-on-workspace-change = [
#   '/bin/bash',
#   '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
# ]


# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

[workspace-to-monitor-force-assignment]
1 = ["LG.*", 'DELL.* \(1\)$', "built-in"]
2 = ["LG.*", 'DELL.* \(1\)$', "built-in"]
3 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
4 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
5 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
6 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
7 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
8 = ["MAG.*", 'DELL.* \(2\)$', "built-in"]
A = "built-in"
B = "built-in"
C = "built-in"
D = "built-in"


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.bottom = 8
outer.left = 8
outer.right = 8
outer.top = 8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout h_accordion horizontal vertical'
alt-period = 'layout v_accordion vertical horizontal'
alt-shift-f = 'layout floating tiling'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'

alt-f = 'fullscreen'
alt-o = 'focus-back-and-forth'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-cmd-ctrl-1 = 'move-node-to-workspace --focus-follows-window 1'
alt-shift-cmd-ctrl-2 = 'move-node-to-workspace --focus-follows-window 2'
alt-shift-cmd-ctrl-3 = 'move-node-to-workspace --focus-follows-window 3'
alt-shift-cmd-ctrl-4 = 'move-node-to-workspace --focus-follows-window 4'
alt-shift-cmd-ctrl-5 = 'move-node-to-workspace --focus-follows-window 5'
alt-shift-cmd-ctrl-6 = 'move-node-to-workspace --focus-follows-window 6'
alt-shift-cmd-ctrl-7 = 'move-node-to-workspace --focus-follows-window 7'
alt-shift-cmd-ctrl-8 = 'move-node-to-workspace --focus-follows-window 8'
alt-shift-cmd-ctrl-a = 'move-node-to-workspace --focus-follows-window A'
alt-shift-cmd-ctrl-b = 'move-node-to-workspace --focus-follows-window B'
alt-shift-cmd-ctrl-c = 'move-node-to-workspace --focus-follows-window C'
alt-shift-cmd-ctrl-d = 'move-node-to-workspace --focus-follows-window D'

#
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-m = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']                # reset layout
backspace = ['close-all-windows-but-current', 'mode main']

# Resize
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
m = ['volume set 0', 'mode main']

# Move apps to the correct workspaces
# Slack
[[on-window-detected]]
if.app-id = 'org.tinyspeck.slackmacgap'
run = 'move-node-to-workspace A'

# Zen Browser
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 1'

# Brave Browser
[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 1'

# Chrome Browser
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

# Spotify
[[on-window-detected]]
if.app-id = 'app.spotify.client'
run = 'move-node-to-workspace B'

# Messages
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace B'

# Ghostty terminal
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
if.during-aerospace-startup = true
run = 'move-node-to-workspace 3'

# Zoom
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['layout floating', 'move-node-to-workspace D']

# Finder
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

# 1Password
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

# Activity Monitor
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'
