
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "  "

[azure]
disabled = true
format = 'on [$symbol($username)]($style) '
symbol = 'ﴃ '
style = 'blue bold'

[jobs]
disabled = false

[kubernetes]
style = "bold #8be9fd"
format = '[$symbol$context( \($namespace\))]($style) in '
disabled = false

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
disabled = false
symbol = " "

[golang]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = "🐍 "
pyenv_version_name = true

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[terraform]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "💠 "

[status]
disabled = false

[git_status]
disabled = false

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[battery]
disabled = true

[directory]
read_only = "(read only)"

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
