[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/run/current-system/sw/bin/nu"

[window]
blur = true
decorations = "none"
dynamic_padding = true
dynamic_title = false
opacity = 0.8

[window.dimensions]
columns = 140
lines = 70

[window.padding]
x = 5
y = 1

[general]
live_config_reload = true

[terminal]
