AMD_VULKAN_ICD=RADV
ENABLE_LAYER_MESA_ANTI_LAG=1
FSR4_UPGRADE=1
MESA_SHADER_CACHE_MAX_SIZE=30G
PROTON_ENABLE_MEDIACONV=1
PROTON_ENABLE_WAYLAND=1
PROTON_FSR4_RDNA3_UPGRADE=1
PROTON_FSR4_UPGRADE=1
PROTON_LOCAL_SHADER_CACHE=1
PROTON_NO_WM_DECORATION=1
PROTON_PREFER_SDL=1
PROTON_USE_NTSYNC=1
WINE_NO_WM_DECORATION=1
